package ucvp;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-03-16T23:17:14.466+08:00
 * Generated source version: 3.1.10
 * 
 */
@WebServiceClient(name = "UCVP_spcAccount_spcUpload_spcWorkflow", 
                  wsdlLocation = "file:/D:/WORK/WorkSpace/Rise/Webservice/src/ucvp/S1102001A_ASMP2ESB_V0.1.wsdl",
                  targetNamespace = "http://siebel.com/AccountUpload") 
public class UCVPSpcAccountSpcUploadSpcWorkflow_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://siebel.com/AccountUpload", "UCVP_spcAccount_spcUpload_spcWorkflow");
    public final static QName UCVPSpcAccountSpcUploadSpcWorkflow = new QName("http://siebel.com/AccountUpload", "UCVP_spcAccount_spcUpload_spcWorkflow");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/WORK/WorkSpace/Rise/Webservice/src/ucvp/S1102001A_ASMP2ESB_V0.1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UCVPSpcAccountSpcUploadSpcWorkflow_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/WORK/WorkSpace/Rise/Webservice/src/ucvp/S1102001A_ASMP2ESB_V0.1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UCVPSpcAccountSpcUploadSpcWorkflow_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UCVPSpcAccountSpcUploadSpcWorkflow_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UCVPSpcAccountSpcUploadSpcWorkflow_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public UCVPSpcAccountSpcUploadSpcWorkflow_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public UCVPSpcAccountSpcUploadSpcWorkflow_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public UCVPSpcAccountSpcUploadSpcWorkflow_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns UCVPSpcAccountSpcUploadSpcWorkflow
     */
    @WebEndpoint(name = "UCVP_spcAccount_spcUpload_spcWorkflow")
    public UCVPSpcAccountSpcUploadSpcWorkflow getUCVPSpcAccountSpcUploadSpcWorkflow() {
        return super.getPort(UCVPSpcAccountSpcUploadSpcWorkflow, UCVPSpcAccountSpcUploadSpcWorkflow.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UCVPSpcAccountSpcUploadSpcWorkflow
     */
    @WebEndpoint(name = "UCVP_spcAccount_spcUpload_spcWorkflow")
    public UCVPSpcAccountSpcUploadSpcWorkflow getUCVPSpcAccountSpcUploadSpcWorkflow(WebServiceFeature... features) {
        return super.getPort(UCVPSpcAccountSpcUploadSpcWorkflow, UCVPSpcAccountSpcUploadSpcWorkflow.class, features);
    }

}
