package com.heimu.model;

import java.util.Date;

public class TtDynamicDataSource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_dynamic_data_source.dbs_name
     *
     * @mbggenerated
     */
    private String dbsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_dynamic_data_source.dbs_driver_class
     *
     * @mbggenerated
     */
    private String dbsDriverClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_dynamic_data_source.dbs_url
     *
     * @mbggenerated
     */
    private String dbsUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_dynamic_data_source.dbs_user_name
     *
     * @mbggenerated
     */
    private String dbsUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_dynamic_data_source.dbs_password
     *
     * @mbggenerated
     */
    private String dbsPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_dynamic_data_source.dbs_status
     *
     * @mbggenerated
     */
    private String dbsStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_dynamic_data_source.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_dynamic_data_source.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_dynamic_data_source.update_by
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_dynamic_data_source.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_dynamic_data_source.dbs_name
     *
     * @return the value of tt_dynamic_data_source.dbs_name
     *
     * @mbggenerated
     */
    public String getDbsName() {
        return dbsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_dynamic_data_source.dbs_name
     *
     * @param dbsName the value for tt_dynamic_data_source.dbs_name
     *
     * @mbggenerated
     */
    public void setDbsName(String dbsName) {
        this.dbsName = dbsName == null ? null : dbsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_dynamic_data_source.dbs_driver_class
     *
     * @return the value of tt_dynamic_data_source.dbs_driver_class
     *
     * @mbggenerated
     */
    public String getDbsDriverClass() {
        return dbsDriverClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_dynamic_data_source.dbs_driver_class
     *
     * @param dbsDriverClass the value for tt_dynamic_data_source.dbs_driver_class
     *
     * @mbggenerated
     */
    public void setDbsDriverClass(String dbsDriverClass) {
        this.dbsDriverClass = dbsDriverClass == null ? null : dbsDriverClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_dynamic_data_source.dbs_url
     *
     * @return the value of tt_dynamic_data_source.dbs_url
     *
     * @mbggenerated
     */
    public String getDbsUrl() {
        return dbsUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_dynamic_data_source.dbs_url
     *
     * @param dbsUrl the value for tt_dynamic_data_source.dbs_url
     *
     * @mbggenerated
     */
    public void setDbsUrl(String dbsUrl) {
        this.dbsUrl = dbsUrl == null ? null : dbsUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_dynamic_data_source.dbs_user_name
     *
     * @return the value of tt_dynamic_data_source.dbs_user_name
     *
     * @mbggenerated
     */
    public String getDbsUserName() {
        return dbsUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_dynamic_data_source.dbs_user_name
     *
     * @param dbsUserName the value for tt_dynamic_data_source.dbs_user_name
     *
     * @mbggenerated
     */
    public void setDbsUserName(String dbsUserName) {
        this.dbsUserName = dbsUserName == null ? null : dbsUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_dynamic_data_source.dbs_password
     *
     * @return the value of tt_dynamic_data_source.dbs_password
     *
     * @mbggenerated
     */
    public String getDbsPassword() {
        return dbsPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_dynamic_data_source.dbs_password
     *
     * @param dbsPassword the value for tt_dynamic_data_source.dbs_password
     *
     * @mbggenerated
     */
    public void setDbsPassword(String dbsPassword) {
        this.dbsPassword = dbsPassword == null ? null : dbsPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_dynamic_data_source.dbs_status
     *
     * @return the value of tt_dynamic_data_source.dbs_status
     *
     * @mbggenerated
     */
    public String getDbsStatus() {
        return dbsStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_dynamic_data_source.dbs_status
     *
     * @param dbsStatus the value for tt_dynamic_data_source.dbs_status
     *
     * @mbggenerated
     */
    public void setDbsStatus(String dbsStatus) {
        this.dbsStatus = dbsStatus == null ? null : dbsStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_dynamic_data_source.create_by
     *
     * @return the value of tt_dynamic_data_source.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_dynamic_data_source.create_by
     *
     * @param createBy the value for tt_dynamic_data_source.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_dynamic_data_source.create_date
     *
     * @return the value of tt_dynamic_data_source.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_dynamic_data_source.create_date
     *
     * @param createDate the value for tt_dynamic_data_source.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_dynamic_data_source.update_by
     *
     * @return the value of tt_dynamic_data_source.update_by
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_dynamic_data_source.update_by
     *
     * @param updateBy the value for tt_dynamic_data_source.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_dynamic_data_source.update_date
     *
     * @return the value of tt_dynamic_data_source.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_dynamic_data_source.update_date
     *
     * @param updateDate the value for tt_dynamic_data_source.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}